name: AOC2
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - snakemake=7.8.2
  - hyphy=2.5.39
  - iqtree=2.1.2
  - tn93=1.0.6
  - altair=4.2.0
  - altair_saver=0.5.0
  - biopython=1.78
  - jupyterlab>=3
  - mafft=7.475
  - python=3.8
  - jupyter=1.0
  - jupyterlab_code_formatter=1.4
